In [1]:
# if this fails, please install numpy :)
import numpy as np

# Getting familiar with numpy and ndarrays

*Any doubt on what you are doing: have a look at [numpy's (very detailed) documentation](https://numpy.org/doc/)*

Using `np.zeros` construct a vector of complexes (double precision) of size $15$

You'll need: `np.zeros`, `np.complex128`

In [3]:
vector = np.zeros((15, ), dtype=np.complex128)
vector = np.random.random((15, ))
print(vector)
# sum a_i |i>

[0.34998076 0.68502947 0.04365875 0.49963894 0.39072351 0.68933888
 0.54269296 0.28126931 0.38742896 0.63980417 0.82065068 0.99512138
 0.76475669 0.69418904 0.85442515]


Is there a natural way of seeing this vector as a $3\times 5$ complex matrix ?

Can you convert it ? (using `np.reshape` or the `.reshape`  method of the `np.ndarray` class)

What if you wanted to directly allocate such a matrix ? (using `np.zeros`)

In [4]:
# sum a_i |i>
# sum b_ij |i><j|
print(np.reshape(vector, (3, 5)))

[[0.34998076 0.68502947 0.04365875 0.49963894 0.39072351]
 [0.68933888 0.54269296 0.28126931 0.38742896 0.63980417]
 [0.82065068 0.99512138 0.76475669 0.69418904 0.85442515]]


Same thing with a vector of length $8$ and a multi-array of shape $2\times 2\times 2$?

In [5]:
vector = np.random.random((8, ))
print(vector.reshape((2, 2, 2)))

[[[0.54372955 0.93553274]
  [0.51687181 0.89712132]]

 [[0.92090153 0.09260365]
  [0.23274392 0.56166547]]]


Same thing with a vector of length $2^n$ and a multi-array of shape $2\times \cdots \times 2$ ?

In [6]:
def do_it_for(n):
    vector = np.random.random((2**n,))
    print(vector.reshape((2, )* n))

do_it_for(5)

[[[[[0.09996453 0.68105102]
    [0.89511884 0.23541227]]

   [[0.17967527 0.10214383]
    [0.82664299 0.71629725]]]


  [[[0.33224961 0.54761942]
    [0.83620011 0.60633256]]

   [[0.07620966 0.87599974]
    [0.1988704  0.4551886 ]]]]



 [[[[0.40334071 0.82674   ]
    [0.57516905 0.6255893 ]]

   [[0.96978021 0.23948022]
    [0.15149608 0.1845052 ]]]


  [[[0.58045098 0.61175452]
    [0.47011979 0.96523867]]

   [[0.85766726 0.12735769]
    [0.90445658 0.3269979 ]]]]]


Meditate upon the fact that this vector represents indeed a vector in the tensor product of $n$ $2$ dimensional Hilbert spaces.

let us assume that such a vector is reshaped as a  $2\times \cdots \times 2$ multi-array $M$.
What does the entry $M[b_1, ..., b_n], b_i\in \{0, 1\}$ represents (in terms of wavefunction/statevector/vector in a $2^n$ dimensional Hilbert space)?

Allocate a vector/multi-array representing state $|0^7\rangle$ over 7 qubits.

In [ ]:
vector = np.random.random((2**3, )).reshape((2, 2, 2))
# |000>, |011>
vector[0, 0, 0]
vector[0, 1, 1]

# |0....0> over 7 qubits
vector = np.zeros((2,) * 7, dtype=np.complex128)
vector[0, 0, 0, 0, 0, 0, 0] = 1.



Allocate a vector/multi-array representing a Bell-state $\frac{|00\rangle + |11\rangle}{\sqrt{2}}$

In [8]:
vector = np.zeros((2,) * 2, dtype=np.complex128)
vector[0, 0] = 1 / np.sqrt(2.)
vector[1, 1] = 1 / np.sqrt(2.)
print(vector.reshape((4, )))


[0.70710678+0.j 0.        +0.j 0.        +0.j 0.70710678+0.j]


# Dots and tensordots

Allocate two random matrices ($n\times k$ and $k \times m$) using `np.random.random` and multiply them using `np.dot`
(pick your favorite non-trivial values for $n,k,m$).

In [9]:
A = np.random.random((2, 3))
B = np.random.random((3, 4))

print(np.dot(A, B))
print(A.dot(B))
print(A @ B)

[[0.33123535 0.41069197 0.45217584 0.44944302]
 [0.83080655 0.80253491 1.15984919 1.05026578]]
[[0.33123535 0.41069197 0.45217584 0.44944302]
 [0.83080655 0.80253491 1.15984919 1.05026578]]
[[0.33123535 0.41069197 0.45217584 0.44944302]
 [0.83080655 0.80253491 1.15984919 1.05026578]]


Comment on the complexity of this operation.

Allocate two random multi-arrays ($n \times k \times l$ and $k \times m \times h$ for instance).

Can you perform a tensordot/generalized between any pair of axes of these arrays ?

If yes, show me. If not, is there a pair of axes between which you can perform a tensordot (show me too)?

You can either use the `.tensordot` method or the `np.tensordot` function.


In [12]:
A = np.random.random((2, 3, 4))
B = np.random.random((3, 5, 6))

result = np.tensordot(A, B, axes=([1], [0]))
print(result.shape)
# (2, 4, 5, 6)


(2, 4, 5, 6)
(2, 4, 5, 6)


Look at the shape of the resulting array. Can you infer how this shape was chosen/generated ?

Allocate two random multi-arrays ($n \times k \times l$ and $k \times m \times l$ for instance).

Same questions but with pairs of pairs:
- is there a pair of axes of the first array that you can tensordot with a pair of axes of the second?

In [13]:
A = np.random.random((2, 3, 7))
B = np.random.random((3, 5, 7))

result = np.tensordot(A, B, axes=([1, 2], [0, 2]))
print(result.shape)

(2, 5)


## Shuffling axes of multi-arrays

Sometimes one needs to move axes around to transform for instance a $n \times k \times l$ array into a $n \times l \times k$ array.

Read the documentation of functions `np.moveaxis` and `np.transpose`.

Which one is the most performant ?
Check it by running a quick benchmark.

In [15]:
import time

N = 15
array = np.random.random((2, ) * N)
permutation = list(range(N))
np.random.shuffle(permutation)

RETRIES = 10000

start = time.time()
for _ in range(RETRIES):
    np.moveaxis(array, source=list(range(N)), destination=permutation)
print(f"With moveaxis: {time.time() - start}s")

start = time.time()
for _ in range(RETRIES):
    np.transpose(array, permutation)
print(f"With transpose: {time.time() - start}s")

With moveaxis: 2.9907724857330322s
With transpose: 0.23366761207580566s


Try to find a sound explanation of this difference.

## The start of a basic simulator

Impress me by:
- allocating a wavefunction over 3 qubits in state $|000\rangle$  (`np.zeros` + some manipulation)
- allocating a $2\times 2$ matrix representing a $H$ gate (`np.array`). Recall that :
$$ H = \frac{1}{\sqrt{2}}\begin{bmatrix}
1 & 1\\
1 & -1
\end{bmatrix}$$

- applying the gate $H$ to the first qubit via:
    - reshaping of the wavefunction into a $2 \times 2 \times 2$ multi-array
    - tensordot between the correct axes of the wavefunction and the $H$ matrix
    - using a `np.transpose` to reorder the axes in their correct positions

Impress me even further by:
- starting from the wavefunction obtained at the end of the previous question
- allocating a $4 \times 4$ matrix corresponding to a CNOT gate. Recall that:
$$ CNOT = \begin{bmatrix}
1 & 0 & 0 & 0\\
0 & 1 & 0 & 0\\
0 & 0 & 0 & 1\\
0 & 0 & 1 & 0
\end{bmatrix} = P_0 \otimes I + P_1 \otimes X$$

- using tensordots/reshapes/tranposes in order to apply gate CNOT on qubits 1 and 2
- using tensordots/reshapes/tranposes in order to apply gate CNOT on qubits 1 and 3

What is the final expected state ? Check it.